### ISSUE TITLE
cluster carousel id/css on tagungen overview

### ISSUE THREAD

**Issue by Duckstein** [Duckstein/morR17#15]
there a six carousels - all with an unique id and class; needed for js/css and arrow-nav. Check possibility to "unify" class/id...

```css
[class*="carousel"] {
    position: absolute;
}
```

will not work...
